### ISSUE TITLE
chemspider_webservices.jar not readily accessible

### ISSUE THREAD

**Issue by PMSeitzer** [c-ruttkies/MetFragRelaunched#4]
chemspider_webservices-1.0.jar is not available on maven central, and  the only chemspider_webservices-1.jar I could locate I found here:
http://www.chemspider.com/blog/how-to-use-chemspider-webservices-when-programming-with-java.html

However, this does not seem to be the proper version.  Attempting to build the project runs into a compilation failure.

Can you make available the chemspider_webservices-1.0.jar, so that the project can be successfully built?

**Comment by c-ruttkies** [comment]
Hi,

thanks for your comment. You are right, the ChemSpider lib is not available on maven central. For that reason we used the guide provided on the ChemSpider website you pasted in your comment. We have compiled the sources with Java 1.6 (provided version seems to compiled with Java 1.7) and the generated jar can be found in our personal repo:

http://msbi.ipb-halle.de/~cruttkie/maven2/

Actually, it should be downloaded automatically by running the maven build command:

mvn clean install -pl MetFragLib -am

Maybe there was a temporal server timeout. I have tested that several times now and it could be downloaded successfully in any case. Could you have another try and maybe paste the error in case it doesn't work. 

Thanks in advance.

Best regards,
Christoph

**Comment by PMSeitzer** [comment]
I was able to get it to work by using the .jar from your personal repo - thank you!
