### ISSUE TITLE
Build fails on macOS SIerra

### ISSUE THREAD

**Issue by JB-MS** [c-ruttkies/MetFragRelaunched#8]
Hi,

MetFrag appears to be very well suited for my current project, so i am looking forward to use it asap in a high-throughput manner.

I have tried to compile MetFragCL via:

`mvn clean install -pl MetFragCommandLine -am `

(fresh brew install of Java and Maven)

And it came up with the following error:

> [ERROR] Failed to execute goal on project MetFragLib: Could not resolve dependencies for project de.ipbhalle.metfraglib:MetFragLib:jar:2.3.1: Failed to collect dependencies at com.chemspider.www:chemspider_webservices:jar:1.0: Failed to read artifact descriptor for com.chemspider.www:chemspider_webservices:jar:1.0: Could not transfer artifact com.chemspider.www:chemspider_webservices:pom:1.0 from/to msbi (http://msbi.ipb-halle.de/~cruttkie/maven2): Access denied to: http://msbi.ipb-halle.de/~cruttkie/maven2/com/chemspider/www/chemspider_webservices/1.0/chemspider_webservices-1.0.pom , ReasonPhrase:Forbidden. -> [Help 1]

Could you please help me getting it to work?

Cheers,
Johannes

**Comment by c-ruttkies** [comment]
Hi Johannes,

you should now be able to access https://msbi.ipb-halle.de/~cruttkie/maven2/com/chemspider/www/chemspider_webservices/1.0/chemspider_webservices-1.0.pom again. Could you please check whether the MetFrag built is successful now.

Best regards,
Christoph

**Comment by JB-MS** [comment]
Hi Christoph,

thanks again :) It works now fine and i was able to build it.

Cheers,
Johannes
